# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: setup ssh key
      env:
        private_key: ${{ secrets.PRIVATE_KEY }}
      run: |
        mkdir -p $GITHUB_WORKSPACE/ssh
        echo "$private_key" > $GITHUB_WORKSPACE/ssh/id_rsa
        chmod 600 $GITHUB_WORKSPACE/ssh/id_rsa
        eval `ssh-agent`
        ssh-add $GITHUB_WORKSPACE/ssh/id_rsa
        ssh-add -l
    - uses: actions/checkout@v2
      with:
        ssh-key: "$private_key"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
